### ISSUE TITLE
Press Enter to Continue  sometimes requires multiple Enter Presses

### ISSUE THREAD

**Issue by mattearly** [mattearly/DM-Power-Core-Version#51]

**Comment by bytePro17124** [comment]
partially resolved, but now flies through the press enter on other occasions

**Comment by mattearly** [comment]
dat newline

**Comment by mattearly** [comment]
C++ console programs and using input, THE ULTIMATE WAR OF DOES IT EAT THE NEWLINE OR DOES IT NOT EAT THE NEWLINE.
